# Generated by Django 2.1 on 2020-07-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20200725_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField(max_length=10)),
                ('address', models.TextField()),
                ('usertype', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=10)),
                ('is_active', models.BooleanField()),
                ('created_at', models.BigIntegerField()),
                ('modified_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
