# Generated by Django 2.1 on 2020-07-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_website', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('inception', models.CharField(max_length=100)),
                ('created_at', models.BigIntegerField()),
                ('modified_at', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Company_Details',
            },
        ),
    ]
