# Generated by Django 2.1 on 2020-07-31 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_companydetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAlumni',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=50)),
                ('referred_by', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('mobile_number', models.IntegerField(max_length=12)),
                ('direct_number', models.IntegerField(max_length=50)),
                ('notes', models.TextField()),
                ('institution', models.CharField(max_length=50)),
                ('institution_name', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('stream', models.CharField(max_length=50)),
                ('total_experience', models.DurationField()),
                ('yop', models.IntegerField()),
                ('degree', models.CharField(max_length=50)),
                ('current_experience', models.DurationField()),
                ('facebook', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('board_line_no', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('pin', models.IntegerField()),
                ('recruitment', models.BooleanField()),
                ('created_at', models.BigIntegerField()),
                ('modified_at', models.BigIntegerField()),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.CompanyDetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.UserDetails')),
            ],
            options={
                'db_table': 'Contact_alumni',
            },
        ),
        migrations.CreateModel(
            name='ExternalMeetings',
            fields=[
                ('meet_id', models.AutoField(primary_key=True, serialize=False)),
                ('agenda', models.CharField(max_length=150)),
                ('meeting_date', models.DateField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('meeting_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_open', models.BooleanField()),
                ('created_at', models.BigIntegerField()),
                ('modified_at', models.BigIntegerField()),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.CompanyDetails')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.ContactAlumni')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.UserDetails')),
            ],
            options={
                'db_table': 'External_Meetings',
            },
        ),
        migrations.CreateModel(
            name='InternalMeeting',
            fields=[
                ('meet_id', models.AutoField(primary_key=True, serialize=False)),
                ('agenda', models.CharField(max_length=150)),
                ('meeting_date', models.DateField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('meeting_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_open', models.BooleanField()),
                ('created_at', models.BigIntegerField()),
                ('modified_at', models.BigIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.UserDetails')),
            ],
            options={
                'db_table': 'Internal_Meetings',
            },
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('tr_id', models.AutoField(primary_key=True, serialize=False)),
                ('travel_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('accompanied_by', models.CharField(max_length=50)),
                ('travel_from', models.CharField(max_length=50)),
                ('travel_to', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
                ('is_open', models.BooleanField()),
                ('created_at', models.BigIntegerField()),
                ('modified_at', models.BigIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.UserDetails')),
            ],
            options={
                'db_table': 'Travel_plan',
            },
        ),
    ]
