# Generated by Django 2.1 on 2021-02-08 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Details',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_website', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('inception', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_alumini',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=50)),
                ('referred_by', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=12)),
                ('direct_number', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('institution', models.CharField(max_length=50)),
                ('institution_name', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('stream', models.CharField(max_length=50)),
                ('total_experience', models.DurationField()),
                ('yop', models.IntegerField()),
                ('degree', models.CharField(max_length=50)),
                ('current_experience', models.DurationField()),
                ('facebook', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('board_line_no', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('pin', models.IntegerField()),
                ('recruitment', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventRestService.Company_Details')),
            ],
        ),
        migrations.CreateModel(
            name='External_Meetings',
            fields=[
                ('meet_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=100)),
                ('agenda', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('meeting_date', models.DateTimeField()),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('assigned_to', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('meeting_type', models.CharField(choices=[('MEETING', 'Meeting'), ('EMAIL', 'Email'), ('PHONE', 'Phone')], default='MEETING', max_length=10)),
                ('description', models.TextField()),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventRestService.Company_Details')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventRestService.Contact_alumini')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='Internal_Meeting',
            fields=[
                ('meet_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('meeting_date', models.DateTimeField()),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('agenda', models.TextField(blank=True, default='', null=True)),
                ('meeting_type', models.CharField(choices=[('ME', 'Meeting'), ('EM', 'Email'), ('PH', 'Phone')], default='ME', max_length=10)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='Office_Types',
            fields=[
                ('office_id', models.AutoField(primary_key=True, serialize=False)),
                ('office_types', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Travel_Plan',
            fields=[
                ('tr_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('travel_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('accompanied_by', models.CharField(blank=True, max_length=50, null=True)),
                ('travel_from', models.CharField(max_length=50)),
                ('travel_to', models.CharField(max_length=50)),
                ('purpose', models.CharField(blank=True, max_length=50, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.user_details')),
            ],
        ),
        migrations.AddField(
            model_name='contact_alumini',
            name='office_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventRestService.Office_Types'),
        ),
        migrations.AddField(
            model_name='contact_alumini',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.user_details'),
        ),
    ]
