# Generated by Django 2.1 on 2020-09-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventRestService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalmeeting',
            name='agenda',
            field=models.TextField(blank=True, null=True),
        ),
    ]
