# Generated by Django 2.1 on 2020-09-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventRestService', '0003_auto_20200904_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalmeetings',
            name='agenda',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='internalmeeting',
            name='agenda',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
