# Generated by Django 2.1 on 2020-09-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventRestService', '0004_auto_20200904_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalmeeting',
            name='agenda',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
