# Generated by Django 2.1 on 2020-09-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventRestService', '0005_auto_20200904_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelplan',
            old_name='Purpose',
            new_name='purpose',
        ),
    ]
