# Generated by Django 2.1 on 2021-04-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0002_auto_20210421_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_local',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100, null=True),
        ),
    ]
