# Generated by Django 2.1 on 2021-05-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='zone',
            field=models.TextField(max_length=25, null=True),
        ),
    ]
