# Generated by Django 2.1 on 2021-02-08 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EventRestService', '__first__'),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assign_company',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventRestService.Company_Details')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.user_details')),
            ],
        ),
        migrations.CreateModel(
            name='internship_info',
            fields=[
                ('internship_id', models.AutoField(primary_key=True, serialize=False)),
                ('intern_profile_ctc', models.CharField(max_length=100)),
                ('intern_batch', models.IntegerField()),
                ('intern_offers', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('intern_remark', models.CharField(max_length=100)),
                ('ppo_offered', models.IntegerField()),
                ('ppo_profile_ctc', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventRestService.Company_Details')),
            ],
        ),
        migrations.CreateModel(
            name='placement_info',
            fields=[
                ('placement_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_ctc', models.CharField(max_length=100)),
                ('batch', models.IntegerField()),
                ('offers', models.IntegerField()),
                ('visit_month', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventRestService.Company_Details')),
            ],
        ),
        migrations.CreateModel(
            name='Placement_Status',
            fields=[
                ('placement_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('placement_status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('stream_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('stream_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hiring.School')),
            ],
        ),
        migrations.AddField(
            model_name='placement_status',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hiring.School'),
        ),
        migrations.AddField(
            model_name='placement_info',
            name='placement_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hiring.Placement_Status'),
        ),
        migrations.AddField(
            model_name='placement_info',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hiring.School'),
        ),
        migrations.AddField(
            model_name='placement_info',
            name='stream_id',
            field=models.ManyToManyField(to='Hiring.Stream'),
        ),
        migrations.AddField(
            model_name='placement_info',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.user_details'),
        ),
        migrations.AddField(
            model_name='internship_info',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hiring.School'),
        ),
        migrations.AddField(
            model_name='internship_info',
            name='stream_id',
            field=models.ManyToManyField(to='Hiring.Stream'),
        ),
        migrations.AddField(
            model_name='internship_info',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.user_details'),
        ),
    ]
