# Generated by Django 2.1 on 2021-03-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hiring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement_info',
            name='placement_status_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
