# Generated by Django 2.1 on 2021-03-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hiring', '0002_auto_20210309_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_info',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship_info',
            name='intern_batch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship_info',
            name='intern_offers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship_info',
            name='intern_profile_ctc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='internship_info',
            name='intern_remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='internship_info',
            name='ppo_offered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship_info',
            name='ppo_profile_ctc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='internship_info',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placement_info',
            name='batch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placement_info',
            name='offers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placement_info',
            name='placement_status_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placement_info',
            name='profile_ctc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='placement_info',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='placement_info',
            name='visit_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
