# Generated by Django 2.1 on 2021-04-11 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
        ('Scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_alumini',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact_alumini',
            name='board_line_no',
        ),
        migrations.RemoveField(
            model_name='contact_alumini',
            name='city',
        ),
        migrations.RemoveField(
            model_name='contact_alumini',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contact_alumini',
            name='office_id',
        ),
        migrations.RemoveField(
            model_name='contact_alumini',
            name='pin',
        ),
        migrations.AddField(
            model_name='contact_alumini',
            name='comp_lcl_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Contact.Company_Local'),
        ),
    ]
