# Generated by Django 2.1 on 2021-04-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0002_auto_20210411_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_alumini',
            name='current_experience',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact_alumini',
            name='total_experience',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
