# Generated by Django 2.1 on 2021-04-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0004_auto_20210422_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_alumini',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
