# Generated by Django 2.1 on 2021-05-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0005_auto_20210423_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_alumini',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact_alumini',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact_alumini',
            name='yop',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
